apiVersion: apps/v1
kind: Deployment
metadata:
  name: department-service
spec:
  replicas: 1

  selector:
    matchLabels:
      app: department-service

  template:
    metadata:
      labels:
        app: department-service

    spec:
      containers:
        - name: department-service
          image: ${IMAGE_NAME}:${IMAGE_TAG}
          imagePullPolicy: Never

          ports:
            - containerPort: 8082

          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://host.minikube.internal:3306/microservice?createDatabaseIfNotExist=true&characterEncoding=UTF-8&serverTimezone=UTC"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "123456"